### ISSUE TITLE
empty mean and error in BNG analysis

### ISSUE THREAD

**Issue by bosby74** [nfsi-canada/OrientPy#11]
Dear,
 trying to reproduce the example in your tutorial for the BNG analysis, I encountered the following error when I tried to launch the command:

bng_average --plot --save CI20.pkl

The output of the command is 

 _|==============================================|
 |                       CI20                   |
 |==============================================|
 |  Station: XT.CI20                            |
 |      Channel: HH; Locations: 00              |
 |      Lon:    6.96; Lat:  45.82               |
 | Input Directory:  BNG_RESULTS
 | Plot Results:  True
 |
 /opt/anaconda3/envs/orient/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
   out=out, **kwargs)
 /opt/anaconda3/envs/orient/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
|    B-N-G mean, error, data included: nan, nan, 0__ 

and no one plot is shown. 
The output of this example is referred to a temporary station of one of the project I am involved, but the same error I got with LOBS3 station as shown in your tutorial.
Do you know what kind of problem is and how to solve it?

Thanks,
Simone

**Comment by juch427** [comment]
Same Error for me when I want to run the example script for station LOBS3 with python 3.8.

**command**: bng_average --plot --save YH_list.pkl

**Meesage**:
|                      LOBS3                   |
|==============================================|
|  Station: YH.LOBS3                           |
|      Channel: HH; Locations: --              |
|      Lon:  179.15; Lat: -38.79               |
| Input Directory:  BNG_RESULTS
| Plot Results:  True
|
/home/user/anaconda3/envs/user/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/envs/user/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
|    B-N-G mean, error, data included: nan, nan, 0

If possible, could you please help us find the problem and solve it?

Thanks,
Juch

**Comment by juch427** [comment]
I tried to solve the problem as follows:
For code script bng_average.py in /OrientPy/orientpy/scripts, in Line 181, modify the str "**Meta_Data.pkl**" to "**Meta_data.pkl**" and re-install it.

**Comment by paudetseis** [comment]
Thanks for this fix - I pushed this change to master.
